platform :ios, '13.0'
inhibit_all_warnings!

target 'Hango' do
  # Network and data
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'MJExtension'

  # UI layout and keyboard
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'MBProgressHUD+JDragon'

  # Media and in-app purchase
  pod 'TZImagePickerController'
  pod 'YBImageBrowser'
  pod 'RMStore'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end

  afnetworking_dir = File.join(__dir__, 'Pods', 'AFNetworking', 'AFNetworking')
  Dir.glob(File.join(afnetworking_dir, '*.{h,m}')).each do |source_file|
    File.chmod(0o644, source_file)
    contents = File.read(source_file)
    next unless contents.include?('netinet6/in6.h')

    contents = contents.gsub("#import <netinet6/in6.h>\n", '')
    File.write(source_file, contents)
  end
end
